package com.lockton.crms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SuperPayload implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("EventAction")
	private java.lang.String eventAction;
	@org.kie.api.definition.type.Label("StartDate")
	private String startDate;
	@org.kie.api.definition.type.Label("ParentProcessID")
	private java.lang.Long parentProcessId;

	@org.kie.api.definition.type.Label("ClientID")
	private java.lang.Integer clientId;

	@org.kie.api.definition.type.Label("PlanYear")
	private java.lang.String planYear;

	@org.kie.api.definition.type.Label("TaskAssignedRole")
	private TaskAssignedRole taskAssignedRole;

	@org.kie.api.definition.type.Label("ProcessName")
	private java.lang.String processName;

	@org.kie.api.definition.type.Label("ProcessID")
	private java.lang.Long processId;

	@org.kie.api.definition.type.Label("MonthOfNewPlanYear")
	private java.lang.String monthOfNewPlanYear;

	@org.kie.api.definition.type.Label("RequestID")
	private String requestId;

	public SuperPayload() {
	}

	public java.lang.String getEventAction() {
		return this.eventAction;
	}

	public void setEventAction(java.lang.String eventAction) {
		this.eventAction = eventAction;
	}

	public java.lang.Long getParentProcessId() {
		return this.parentProcessId;
	}

	public void setParentProcessId(java.lang.Long parentProcessId) {
		this.parentProcessId = parentProcessId;
	}

	public java.lang.Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(java.lang.Integer clientId) {
		this.clientId = clientId;
	}

	public java.lang.String getPlanYear() {
		return this.planYear;
	}

	public void setPlanYear(java.lang.String planYear) {
		this.planYear = planYear;
	}

	public com.lockton.crms.TaskAssignedRole getTaskAssignedRole() {
		return this.taskAssignedRole;
	}

	public void setTaskAssignedRole(
			com.lockton.crms.TaskAssignedRole taskAssignedRole) {
		this.taskAssignedRole = taskAssignedRole;
	}

	public java.lang.String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.lang.String startDate) {
		this.startDate = startDate;
	}

	public java.lang.String getProcessName() {
		return this.processName;
	}

	public void setProcessName(java.lang.String processName) {
		this.processName = processName;
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public java.lang.String getMonthOfNewPlanYear() {
		return this.monthOfNewPlanYear;
	}

	public void setMonthOfNewPlanYear(java.lang.String monthOfNewPlanYear) {
		this.monthOfNewPlanYear = monthOfNewPlanYear;
	}

	public java.lang.String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(java.lang.String requestId) {
		this.requestId = requestId;
	}

	public SuperPayload(java.lang.String eventAction,
			java.lang.String startDate, java.lang.Long parentProcessId,
			java.lang.Integer clientId, java.lang.String planYear,
			com.lockton.crms.TaskAssignedRole taskAssignedRole,
			java.lang.String processName, java.lang.Long processId,
			java.lang.String monthOfNewPlanYear, java.lang.String requestId) {
		this.eventAction = eventAction;
		this.startDate = startDate;
		this.parentProcessId = parentProcessId;
		this.clientId = clientId;
		this.planYear = planYear;
		this.taskAssignedRole = taskAssignedRole;
		this.processName = processName;
		this.processId = processId;
		this.monthOfNewPlanYear = monthOfNewPlanYear;
		this.requestId = requestId;
	}

}