package com.lockton.crms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Task implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Assigned")
	private com.lockton.crms.User assigned;
	@org.kie.api.definition.type.Label("ContainerId")
	private java.lang.String containerId;
	@org.kie.api.definition.type.Label("DueDate")
	private java.lang.String dueDate;
	@org.kie.api.definition.type.Label("EventAction")
	private java.lang.String eventAction;
	@org.kie.api.definition.type.Label("ParentProcessId")
	private Long parentProcessId;
	@org.kie.api.definition.type.Label("PeerReviewUser")
	private com.lockton.crms.User peerReviewUser;
	@org.kie.api.definition.type.Label("PeerReview")
	private java.lang.String peerReview;
	@org.kie.api.definition.type.Label("StartDate")
	private java.lang.String startDate;
	@org.kie.api.definition.type.Label("TaskAction")
	private java.lang.String taskAction;
	@org.kie.api.definition.type.Label("TaskId")
	private Long taskId;
	@org.kie.api.definition.type.Label("TaskName")
	private java.lang.String taskName;

	@org.kie.api.definition.type.Label("ReAssignedUser")
	private com.lockton.crms.User reassignedUser;

	@org.kie.api.definition.type.Label("NextTaskDueDate")
	private java.lang.String nextTaskDueDate;

	@org.kie.api.definition.type.Label("ProcessID")
	private java.lang.Long processId;

	@org.kie.api.definition.type.Label("RequestID")
	private String requestId;

	public Task() {
	}

	public com.lockton.crms.User getAssigned() {
		return this.assigned;
	}

	public void setAssigned(com.lockton.crms.User assigned) {
		this.assigned = assigned;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.String getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(java.lang.String dueDate) {
		this.dueDate = dueDate;
	}

	public java.lang.String getEventAction() {
		return this.eventAction;
	}

	public void setEventAction(java.lang.String eventAction) {
		this.eventAction = eventAction;
	}

	public com.lockton.crms.User getPeerReviewUser() {
		return this.peerReviewUser;
	}

	public void setPeerReviewUser(com.lockton.crms.User peerReviewUser) {
		this.peerReviewUser = peerReviewUser;
	}

	public java.lang.String getPeerReview() {
		return this.peerReview;
	}

	public void setPeerreview(java.lang.String peerReview) {
		this.peerReview = peerReview;
	}

	public java.lang.String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.lang.String startDate) {
		this.startDate = startDate;
	}

	public java.lang.String getTaskAction() {
		return this.taskAction;
	}

	public void setTaskAction(java.lang.String taskAction) {
		this.taskAction = taskAction;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public com.lockton.crms.User getReassignedUser() {
		return this.reassignedUser;
	}

	public void setReassignedUser(com.lockton.crms.User reassignedUser) {
		this.reassignedUser = reassignedUser;
	}

	public java.lang.String getNextTaskDueDate() {
		return this.nextTaskDueDate;
	}

	public void setNextTaskDueDate(java.lang.String nextTaskDueDate) {
		this.nextTaskDueDate = nextTaskDueDate;
	}

	public java.lang.Long getParentProcessId() {
		return this.parentProcessId;
	}

	public void setParentProcessId(java.lang.Long parentProcessId) {
		this.parentProcessId = parentProcessId;
	}

	public java.lang.Long getTaskId() {
		return this.taskId;
	}

	public void setTaskId(java.lang.Long taskId) {
		this.taskId = taskId;
	}

	public java.lang.Long getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.Long processId) {
		this.processId = processId;
	}

	public java.lang.String getRequestId() {
		return this.requestId;
	}

	public void setRequestId(java.lang.String requestId) {
		this.requestId = requestId;
	}

	public Task(com.lockton.crms.User assigned, java.lang.String containerId,
			java.lang.String dueDate, java.lang.String eventAction,
			java.lang.Long parentProcessId,
			com.lockton.crms.User peerReviewUser, java.lang.String peerReview,
			java.lang.String startDate, java.lang.String taskAction,
			java.lang.Long taskId, java.lang.String taskName,
			com.lockton.crms.User reassignedUser,
			java.lang.String nextTaskDueDate, java.lang.Long processId,
			java.lang.String requestId) {
		this.assigned = assigned;
		this.containerId = containerId;
		this.dueDate = dueDate;
		this.eventAction = eventAction;
		this.parentProcessId = parentProcessId;
		this.peerReviewUser = peerReviewUser;
		this.peerReview = peerReview;
		this.startDate = startDate;
		this.taskAction = taskAction;
		this.taskId = taskId;
		this.taskName = taskName;
		this.reassignedUser = reassignedUser;
		this.nextTaskDueDate = nextTaskDueDate;
		this.processId = processId;
		this.requestId = requestId;
	}

}