package com.lockton.crms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TaskAssignedRole implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private User system;
	private User admin;
	private User peerReviewer;
	private User processManager;
	private User processOwner;
	private User processAssociate;
	private User producer;
	private User sme;
	private User client;
	private User vendor;
	private User externalSystem;

	@org.kie.api.definition.type.Label(value = "Role")
	private java.lang.String role;

	public TaskAssignedRole() {
	}

	public com.lockton.crms.User getPeerreviewer() {
		return this.peerReviewer;
	}

	public void setPeerreviewer(com.lockton.crms.User peerReviewer) {
		this.peerReviewer = peerReviewer;
	}

	public com.lockton.crms.User getProcessmanager() {
		return this.processManager;
	}

	public void setProcessmanager(com.lockton.crms.User processManager) {
		this.processManager = processManager;
	}

	public com.lockton.crms.User getProcessowner() {
		return this.processOwner;
	}

	public void setProcessowner(com.lockton.crms.User processOwner) {
		this.processOwner = processOwner;
	}

	public com.lockton.crms.User getProcessassociate() {
		return this.processAssociate;
	}

	public void setProcessassociate(com.lockton.crms.User processAssociate) {
		this.processAssociate = processAssociate;
	}

	public com.lockton.crms.User getExternalsystem() {
		return this.externalSystem;
	}

	public void setExternalsystem(com.lockton.crms.User externalSystem) {
		this.externalSystem = externalSystem;
	}

	public com.lockton.crms.User getSystem() {
		return this.system;
	}

	public void setSystem(com.lockton.crms.User system) {
		this.system = system;
	}

	public com.lockton.crms.User getAdmin() {
		return this.admin;
	}

	public void setAdmin(com.lockton.crms.User admin) {
		this.admin = admin;
	}

	public com.lockton.crms.User getPeerReviewer() {
		return this.peerReviewer;
	}

	public void setPeerReviewer(com.lockton.crms.User peerReviewer) {
		this.peerReviewer = peerReviewer;
	}

	public com.lockton.crms.User getProcessManager() {
		return this.processManager;
	}

	public void setProcessManager(com.lockton.crms.User processManager) {
		this.processManager = processManager;
	}

	public com.lockton.crms.User getProcessOwner() {
		return this.processOwner;
	}

	public void setProcessOwner(com.lockton.crms.User processOwner) {
		this.processOwner = processOwner;
	}

	public com.lockton.crms.User getProcessAssociate() {
		return this.processAssociate;
	}

	public void setProcessAssociate(com.lockton.crms.User processAssociate) {
		this.processAssociate = processAssociate;
	}

	public com.lockton.crms.User getProducer() {
		return this.producer;
	}

	public void setProducer(com.lockton.crms.User producer) {
		this.producer = producer;
	}

	public com.lockton.crms.User getSme() {
		return this.sme;
	}

	public void setSme(com.lockton.crms.User sme) {
		this.sme = sme;
	}

	public com.lockton.crms.User getClient() {
		return this.client;
	}

	public void setClient(com.lockton.crms.User client) {
		this.client = client;
	}

	public com.lockton.crms.User getVendor() {
		return this.vendor;
	}

	public void setVendor(com.lockton.crms.User vendor) {
		this.vendor = vendor;
	}

	public com.lockton.crms.User getExternalSystem() {
		return this.externalSystem;
	}

	public void setExternalSystem(com.lockton.crms.User externalSystem) {
		this.externalSystem = externalSystem;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public TaskAssignedRole(com.lockton.crms.User system,
			com.lockton.crms.User admin, com.lockton.crms.User peerReviewer,
			com.lockton.crms.User processManager,
			com.lockton.crms.User processOwner,
			com.lockton.crms.User processAssociate,
			com.lockton.crms.User producer, com.lockton.crms.User sme,
			com.lockton.crms.User client, com.lockton.crms.User vendor,
			com.lockton.crms.User externalSystem, java.lang.String role) {
		this.system = system;
		this.admin = admin;
		this.peerReviewer = peerReviewer;
		this.processManager = processManager;
		this.processOwner = processOwner;
		this.processAssociate = processAssociate;
		this.producer = producer;
		this.sme = sme;
		this.client = client;
		this.vendor = vendor;
		this.externalSystem = externalSystem;
		this.role = role;
	}
}