package com.lockton.crms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("userName")
	private java.lang.String userName;
	@org.kie.api.definition.type.Label(value = "Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "Role")
	private java.lang.String role;

	public User() {
	}

	public java.lang.String getUserName() {
		return this.userName;
	}

	public void setUserName(java.lang.String userName) {
		this.userName = userName;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public User(java.lang.String userName, java.lang.String email,
			java.lang.String role) {
		this.userName = userName;
		this.email = email;
		this.role = role;
	}

}